package com.masterFrame.runners;


import io.cucumber.junit.Cucumber;
import io.cucumber.junit.CucumberOptions;
import org.junit.runner.RunWith;


@RunWith(Cucumber.class)
@CucumberOptions(

        features = "@target/rerun.txt",
        glue = "com/masterFrame/step_definitions"
)


public class FailedTestRunner {


}

/*
This is a JUnit test runner class for re-running failed Cucumber scenarios. It uses the Cucumber JUnit runner, which allows Cucumber scenarios to be executed as JUnit tests.

The class is annotated with @RunWith(Cucumber.class), which tells JUnit to use the Cucumber runner to execute the tests. The @CucumberOptions annotation provides configuration options for the Cucumber runner.

In this case, the features option is set to "@target/rerun.txt", which specifies that the runner should execute the scenarios listed in the rerun.txt file generated by the previous test run. This file contains the paths to the feature files that contain the failed scenarios.

The glue option is set to "com/masterFrame/step_definitions", which specifies the package where the step definition classes for the scenarios are located.

When this runner is executed, it will re-run only the failed scenarios from the previous test run, using the step definitions defined in the com/masterFrame/step_definitions package.
 */